apiVersion: v1
kind: Service
metadata:
  name: blog-service
spec:
  selector:
    app: blog   # Match labels with your deployment
  ports:
    - protocol: TCP
      port: 8000      # Port on which your Django application is running inside the pod
      targetPort: 8000  # Port on which your Django application is listening inside the pod
  type: NodePort      # Expose the service on a port on each node in the cluster
